<?php
    $rutaEspecialidad = $_GET["pagina"];

    // Llamar al controlador
    $especialistas = ControladorEspecialistas::ctrMostrarEspecialistas($rutaEspecialidad);

    // Convertir array PHP a JSON para JS
    $especialistasJSON = json_encode($especialistas, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
?>

<!-- Main Content -->
<main class="p-4 md:p-6 lg:p-8 max-w-7xl mx-auto space-y-6">
  <!-- Specialists Navigation -->
  <div>
    <div class="flex gap-3 overflow-x-auto pb-2" id="specialists-nav">
      <!-- Specialist buttons will be generated by JavaScript -->
    </div>
  </div>

  <!-- Formulario que envia los datos -->
  <form action="<?php echo $ruta; ?>agenda" method="POST" id="appointment-form">
    <!-- Mobile Layout -->
    <div class="lg:hidden space-y-6">
      <!-- Specialist Details -->
      <div id="specialist-details-mobile">
        <!-- Content will be generated by JavaScript -->
      </div>

      <!-- Certifications Card -->
      <div
        class="bg-fondo-principal rounded-2xl p-6 shadow-sm border border-borde"
        id="certifications-card-mobile"
      >
        <div class="flex items-center gap-3 mb-6">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="lucide lucide-star-icon lucide-star w-5 lg:w-7 h-5 lg:h-7 text-primario"
          >
            <path
              d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"
            />
          </svg>
          <h3>Certificaciones</h3>
        </div>
        <div class="space-y-4" id="certifications-list-mobile">
          <!-- Certifications will be generated by JavaScript -->
        </div>
      </div>

      <!-- Calendar/Time Picker Section (Mobile) -->
      <div>
        <h3 id="appointment-title-mobile">
          Agendar Cita con Dr. María González
        </h3>
        <small>Selecciona la fecha y hora de tu preferencia</small>

        <div class="flex border-b border-borde my-6">
          <button
            type="button"
            id="tab-date-mobile"
            class="flex-1 btn bg-transparent border-0 rounded-none shadow-none border-b-2 border-primario text-boton-secundario-texto cursor-pointer"
          >
            <div class="flex items-center justify-center gap-2">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-calendar-icon lucide-calendar w-5 h-5"
              >
                <path d="M8 2v4" />
                <path d="M16 2v4" />
                <rect width="18" height="18" x="3" y="4" rx="2" />
                <path d="M3 10h18" />
              </svg>
              Fecha
            </div>
          </button>
          <button
            type="button"
            id="tab-time-mobile"
            class="flex-1 btn bg-transparent border-0 rounded-none shadow-none border-b-2 border-borde text-boton-suave-texto cursor-pointer"
          >
            <div class="flex items-center justify-center gap-2">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-clock4-icon lucide-clock-4 w-5 h-5"
              >
                <path d="M12 6v6l4 2" />
                <circle cx="12" cy="12" r="10" />
              </svg>
              Hora
            </div>
          </button>
        </div>

        <div id="date-view-mobile">
          <h4>Selecciona una fecha</h4>
          <small class="mb-4 inline-block">Los domingos no hay atención</small>

          <div class="flex items-center justify-between mb-4">
            <button
              type="button"
              id="prev-month-mobile"
              class="p-2 cursor-pointer btn suave bg-transparent border border-borde rounded-full w-fit"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-chevron-left-icon lucide-chevron-left w-5 h-5"
              >
                <path d="m15 18-6-6 6-6" />
              </svg>
            </button>
            <h5 id="current-month-year-mobile"></h5>
            <button
              type="button"
              id="next-month-mobile"
              class="p-2 cursor-pointer btn suave bg-transparent border border-borde rounded-full w-fit"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-chevron-right-icon lucide-chevron-right w-5 h-5"
              >
                <path d="m9 18 6-6-6-6" />
              </svg>
            </button>
          </div>

          <div class="calendar-grid mb-4">
            <h5 class="text-center py-2">Do</h5>
            <h5 class="text-center py-2">Lu</h5>
            <h5 class="text-center py-2">Ma</h5>
            <h5 class="text-center py-2">Mi</h5>
            <h5 class="text-center py-2">Ju</h5>
            <h5 class="text-center py-2">Vi</h5>
            <h5 class="text-center py-2">Sá</h5>
          </div>
          <div class="calendar-grid" id="calendar-grid-mobile">
            <!-- Calendar days will be generated by JavaScript -->
          </div>
        </div>

        <div id="time-view-mobile" style="display: none">
          <h4>Selecciona una hora</h4>
          <small
            class="mb-4 inline-block"
            id="selected-date-display-mobile"
          ></small>
          <div class="grid grid-cols-3 gap-3" id="time-slots-grid-mobile">
            <!-- Time slots will be generated by JavaScript -->
          </div>
        </div>
      </div>

      <!-- Appointment Summary (Mobile) -->
      <div
        class="bg-fondo-principal rounded-2xl p-6 shadow-sm border border-borde"
        id="appointment-summary-mobile"
        style="display: none"
      >
        <h3 class="mb-6">Resumen de la Cita</h3>

        <div class="space-y-6">
          <!-- Specialty -->
          <div>
            <h4 class="mb-2">Especialidad</h4>
            <p
              class="encabezado bg-estatus-neutral-bg text-estatus-neutral-texto rounded-lg"
              id="summary-specialty-mobile"
            >
              Ortodoncia
            </p>
          </div>

          <!-- Specialist -->
          <div>
            <h4 class="mb-2">Especialista</h4>
            <div class="flex items-center gap-2">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-stethoscope-icon lucide-stethoscope w-4 h-4 md:w-5 md:h-5 lg:w-6 lg:h-6 text-primario"
              >
                <path d="M11 2v2" />
                <path d="M5 2v2" />
                <path
                  d="M5 3H4a2 2 0 0 0-2 2v4a6 6 0 0 0 12 0V5a2 2 0 0 0-2-2h-1"
                />
                <path d="M8 15a6 6 0 0 0 12 0v-3" />
                <circle cx="20" cy="10" r="2" />
              </svg>
              <p id="summary-doctor-mobile">Dr. María González</p>
            </div>
          </div>

          <!-- Date and Time -->
          <div>
            <h4 class="mb-2">Fecha y Hora</h4>
            <div class="space-y-2">
              <div class="flex items-center gap-2">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="lucide lucide-calendar-icon lucide-calendar w-4 h-4 md:w-5 md:h-5 lg:w-6 lg:h-6 text-primario"
                >
                  <path d="M8 2v4" />
                  <path d="M16 2v4" />
                  <rect width="18" height="18" x="3" y="4" rx="2" />
                  <path d="M3 10h18" />
                </svg>
                <p id="summary-date-mobile">martes, 22 de julio de 2025</p>
              </div>
              <div class="flex items-center gap-2">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="lucide lucide-clock4-icon lucide-clock-4 w-4 h-4 md:w-5 md:h-5 lg:w-6 lg:h-6 text-primario"
                >
                  <path d="M12 6v6l4 2" />
                  <circle cx="12" cy="12" r="10" />
                </svg>
                <p id="summary-time-mobile">16:00</p>
              </div>
            </div>
          </div>

          <!-- Inputs ocultos para enviar -->
          <input type="hidden" name="especialidad" id="input-especialidad" />
          <input
            type="hidden"
            name="id_especialista"
            id="input-id-especialista"
          />
          <input type="hidden" name="especialista" id="input-especialista" />
          <input type="hidden" name="fecha" id="input-fecha" />
          <input type="hidden" name="hora" id="input-hora" />

          <!-- Validation Button -->
          <button
            type="submit"
            id="submit-appointment-mobile"
            class="flex justify-center items-center focus:outline-none gap-2 btn primario cursor-pointer"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="lucide lucide-circle-check-big-icon lucide-circle-check-big w-5 h-5"
            >
              <path d="M21.801 10A10 10 0 1 1 17 3.335" />
              <path d="m9 11 3 3L22 4" />
            </svg>
            Validar Disponibilidad
          </button>

          <small>
            Verificaremos la disponibilidad del especialista en la fecha
            seleccionada
          </small>
        </div>
      </div>
    </div>

    <!-- Desktop Layout -->
    <div class="hidden lg:block">
      <!-- Top Section: Specialist Info + Image + Certifications -->
      <div class="grid lg:grid-cols-3 gap-6 mb-6">
        <!-- Specialist Details + Image -->
        <div class="lg:col-span-2">
          <div class="p-6">
            <div
              class="grid md:grid-cols-2 gap-6"
              id="specialist-details-desktop"
            >
              <!-- Content will be generated by JavaScript -->
            </div>
          </div>
        </div>

        <!-- Certifications -->
        <div
          class="bg-fondo-principal rounded-2xl p-6 shadow-sm border border-borde"
          id="certifications-card-desktop"
        >
          <div class="flex items-center gap-3 mb-6">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="lucide lucide-star-icon lucide-star w-5 lg:w-7 h-5 lg:h-7 text-primario"
            >
              <path
                d="M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"
              />
            </svg>
            <h3>Certificaciones</h3>
          </div>
          <div class="space-y-4" id="certifications-list-desktop">
            <!-- Certifications will be generated by JavaScript -->
          </div>
        </div>
      </div>

      <!-- Bottom Section: Calendar + Summary -->
      <div class="grid lg:grid-cols-3 gap-6">
        <!-- Calendar/Time Picker Section (Desktop) -->
        <div class="lg:col-span-2 p-6">
          <h3 id="appointment-title-desktop">
            Agendar Cita con Dr. María González
          </h3>
          <small class="mb-6 inline-block"
            >Selecciona la fecha y hora de tu preferencia</small
          >

          <div class="flex border-b border-borde mb-6">
            <button
              type="button"
              id="tab-date-desktop"
              class="flex-1 btn primario bg-transparent border-0 rounded-none shadow-none border-b-2 border-primario cursor-pointer"
            >
              <div class="flex items-center justify-center gap-2">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="lucide lucide-calendar-icon lucide-calendar w-5 h-5"
                >
                  <path d="M8 2v4" />
                  <path d="M16 2v4" />
                  <rect width="18" height="18" x="3" y="4" rx="2" />
                  <path d="M3 10h18" />
                </svg>
                Fecha
              </div>
            </button>
            <button
              type="button"
              id="tab-time-desktop"
              class="flex-1 btn primario bg-transparent border-0 rounded-none shadow-none border-b-2 border-primario cursor-pointer"
            >
              <div class="flex items-center justify-center gap-2">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="lucide lucide-clock4-icon lucide-clock-4 w-5 h-5"
                >
                  <path d="M12 6v6l4 2" />
                  <circle cx="12" cy="12" r="10" />
                </svg>
                Hora
              </div>
            </button>
          </div>

          <div id="date-view-desktop">
            <h4>Selecciona una fecha</h4>
            <small class="mb-4 inline-block"
              >Los domingos no hay atención</small
            >

            <div class="flex items-center justify-between mb-4">
              <button
                type="button"
                id="prev-month-desktop"
                class="p-2 cursor-pointer btn suave bg-transparent border border-borde rounded-full w-fit"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="lucide lucide-chevron-left-icon lucide-chevron-left w-5 h-5"
                >
                  <path d="m15 18-6-6 6-6" />
                </svg>
              </button>
              <h5 id="current-month-year-desktop"></h5>
              <button
                type="button"
                id="next-month-desktop"
                class="p-2 cursor-pointer btn suave bg-transparent border border-borde rounded-full w-fit"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="lucide lucide-chevron-right-icon lucide-chevron-right w-5 h-5"
                >
                  <path d="m9 18 6-6-6-6" />
                </svg>
              </button>
            </div>

            <div class="calendar-grid mb-4">
              <h5 class="text-center py-2">Do</h5>
              <h5 class="text-center py-2">Lu</h5>
              <h5 class="text-center py-2">Ma</h5>
              <h5 class="text-center py-2">Mi</h5>
              <h5 class="text-center py-2">Ju</h5>
              <h5 class="text-center py-2">Vi</h5>
              <h5 class="text-center py-2">Sá</h5>
            </div>
            <div class="calendar-grid" id="calendar-grid-desktop">
              <!-- Calendar days will be generated by JavaScript -->
            </div>
          </div>

          <div id="time-view-desktop" style="display: none">
            <h4>Selecciona una hora</h4>
            <small
              class="mb-4 inline-block"
              id="selected-date-display-desktop"
            ></small>
            <div class="grid grid-cols-3 gap-3" id="time-slots-grid-desktop">
              <!-- Time slots will be generated by JavaScript -->
            </div>
          </div>
        </div>

        <!-- Appointment Summary (Desktop) -->
        <div
          class="bg-fondo-principal rounded-2xl p-6 shadow-sm border border-borde"
          id="appointment-summary-desktop"
          style="display: none"
        >
          <h3 class="mb-6">Resumen de la Cita</h3>

          <div class="space-y-6">
            <!-- Specialty -->
            <div>
              <h4 class="mb-2">Especialidad</h4>
              <p
                class="encabezado bg-estatus-neutral-bg text-estatus-neutral-texto rounded-lg"
                id="summary-specialty-desktop"
              >
                Ortodoncia
              </p>
            </div>

            <!-- Specialist -->
            <div>
              <h4 class="mb-2">Especialista</h4>
              <div class="flex items-center gap-2">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="lucide lucide-stethoscope-icon lucide-stethoscope w-4 h-4 md:w-5 md:h-5 lg:w-6 lg:h-6 text-primario"
                >
                  <path d="M11 2v2" />
                  <path d="M5 2v2" />
                  <path
                    d="M5 3H4a2 2 0 0 0-2 2v4a6 6 0 0 0 12 0V5a2 2 0 0 0-2-2h-1"
                  />
                  <path d="M8 15a6 6 0 0 0 12 0v-3" />
                  <circle cx="20" cy="10" r="2" />
                </svg>
                <p id="summary-doctor-desktop">Dr. María González</p>
              </div>
            </div>

            <!-- Date and Time -->
            <div>
              <h4 class="mb-2">Fecha y Hora</h4>
              <div class="space-y-2">
                <div class="flex items-center gap-2">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="lucide lucide-calendar-icon lucide-calendar w-4 h-4 md:w-5 md:h-5 lg:w-6 lg:h-6 text-primario"
                  >
                    <path d="M8 2v4" />
                    <path d="M16 2v4" />
                    <rect width="18" height="18" x="3" y="4" rx="2" />
                    <path d="M3 10h18" />
                  </svg>
                  <p id="summary-date-desktop">martes, 22 de julio de 2025</p>
                </div>
                <div class="flex items-center gap-2">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    class="lucide lucide-clock4-icon lucide-clock-4 w-4 h-4 md:w-5 md:h-5 lg:w-6 lg:h-6 text-primario"
                  >
                    <path d="M12 6v6l4 2" />
                    <circle cx="12" cy="12" r="10" />
                  </svg>
                  <p id="summary-time-desktop">16:00</p>
                </div>
              </div>
            </div>

            <!-- Validation Button -->
            <button
              type="submit"
              id="submit-appointment-desktop"
              class="w-full flex justify-center items-center focus:outline-none gap-2 btn primario cursor-pointer"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="lucide lucide-circle-check-big-icon lucide-circle-check-big w-5 h-5"
              >
                <path d="M21.801 10A10 10 0 1 1 17 3.335" />
                <path d="m9 11 3 3L22 4" />
              </svg>
              <span>Validar Disponibilidad</span>
            </button>

            <small>
              Verificaremos la disponibilidad del especialista en la fecha
              seleccionada
            </small>
          </div>
        </div>
      </div>
    </div>
  </form>
</main>

<script>
  // Datos de especialistas obtenidos del backend
  const specialists = <?php echo $especialistasJSON; ?>;
</script>
